@ApiFlow.Api_HostAddress = http://localhost:5085

GET {{ApiFlow.Api_HostAddress}}/api/profiles
Accept: application/json

###

POST {{ApiFlow.Api_HostAddress}}/api/profiles
Content-Type: application/json

{
  "name": "seis",
  "username": "online",
  "password": "change-me",
  "apiKey": "change-me",
  "firmaKodu": 1,
  "donemKodu": 6
}

###

GET {{ApiFlow.Api_HostAddress}}/api/integrations/operations
Accept: application/json

###

POST {{ApiFlow.Api_HostAddress}}/api/integrations/operations
Content-Type: application/json

{
  "key": "stok-listesi",
  "httpMethod": "POST",
  "path": "/api/items",
  "requestBodyTemplate": "{\"limit\":{{limit}},\"offset\":{{offset}},\"filters\":{{filters}}}",
  "headersJson": "{\"Authorization\":\"Bearer {{sessionId}}\"}",
  "resultJsonPath": "result"
}

###

POST {{ApiFlow.Api_HostAddress}}/api/integrations/profiles/1/operations/stok-listesi
Content-Type: application/json

{
  "forceLogin": true,
  "limit": 100,
  "offset": 0
}
